// Auto-generated from porra-data CSV — do not edit manually
// Maps participant ID → tournament final predictions

export interface ParticipantFinals {
  finalista1: string;
  finalista2: string;
  campeon: string;
}

export const PARTICIPANT_FINALS: Record<string, ParticipantFinals> = {
  '1': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '2': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '3': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '4': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '5': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '6': { finalista1: 'ESPAÑA', finalista2: 'ARGENTINA', campeon: 'ESPAÑA' },
  '7': { finalista1: 'ESPAÑA', finalista2: 'ARGENTINA', campeon: 'ESPAÑA' },
  '8': { finalista1: 'FRANCIA', finalista2: 'INGLATERRA', campeon: 'FRANCIA' },
  '9': { finalista1: 'ESPAÑA', finalista2: 'INGLATERRA', campeon: 'ESPAÑA' },
  '10': { finalista1: 'ESPAÑA', finalista2: 'ARGENTINA', campeon: 'ESPAÑA' },
  '11': { finalista1: 'ESPAÑA', finalista2: 'INGLATERRA', campeon: 'ESPAÑA' },
  '12': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '13': { finalista1: 'ESPAÑA', finalista2: 'INGLATERRA', campeon: 'ESPAÑA' },
  '14': { finalista1: 'INGLATERRA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '15': { finalista1: 'ESPAÑA', finalista2: 'ARGENTINA', campeon: 'ESPAÑA' },
  '16': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '17': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '18': { finalista1: 'ESPAÑA', finalista2: 'ARGENTINA', campeon: 'ESPAÑA' },
  '19': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '20': { finalista1: 'ESPAÑA', finalista2: 'ARGENTINA', campeon: 'ESPAÑA' },
  '21': { finalista1: 'PAÍSES BAJOS', finalista2: 'ESPAÑA', campeon: 'ESPAÑA' },
  '22': { finalista1: 'ESPAÑA', finalista2: 'INGLATERRA', campeon: 'ESPAÑA' },
  '24': { finalista1: 'FRANCIA', finalista2: 'PAÍSES BAJOS', campeon: 'PAÍSES BAJOS' },
  '25': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '26': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '27': { finalista1: 'ESPAÑA', finalista2: 'BRASIL', campeon: 'ESPAÑA' },
  '28': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '29': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '30': { finalista1: 'ESPAÑA', finalista2: 'INGLATERRA', campeon: 'ESPAÑA' },
  '31': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'FRANCIA' },
  '32': { finalista1: 'FRANCIA', finalista2: 'ARGENTINA', campeon: 'FRANCIA' },
  '33': { finalista1: 'ESPAÑA', finalista2: 'INGLATERRA', campeon: 'ESPAÑA' },
  '34': { finalista1: 'FRANCIA', finalista2: 'INGLATERRA', campeon: 'FRANCIA' },
  '35': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '36': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '37': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '38': { finalista1: 'ESPAÑA', finalista2: 'ARGENTINA', campeon: 'ARGENTINA' },
  '39': { finalista1: 'ALEMANIA', finalista2: 'BRASIL', campeon: 'BRASIL' },
  '40': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'FRANCIA' },
  '41': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'FRANCIA' },
  '42': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '43': { finalista1: 'ESPAÑA', finalista2: 'BRASIL', campeon: 'ESPAÑA' },
  '44': { finalista1: 'FRANCIA', finalista2: 'BRASIL', campeon: 'BRASIL' },
  '45': { finalista1: 'ESPAÑA', finalista2: 'ARGENTINA', campeon: 'ESPAÑA' },
  '46': { finalista1: 'ESPAÑA', finalista2: 'ARGENTINA', campeon: 'ESPAÑA' },
  '47': { finalista1: 'ESPAÑA', finalista2: 'FRANCIA', campeon: 'ESPAÑA' },
  '48': { finalista1: 'ESPAÑA', finalista2: 'BRASIL', campeon: 'ESPAÑA' },
  '49': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'FRANCIA' },
  '50': { finalista1: 'FRANCIA', finalista2: 'INGLATERRA', campeon: 'FRANCIA' },
  '51': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '52': { finalista1: 'ESPAÑA', finalista2: 'BRASIL', campeon: 'ESPAÑA' },
  '53': { finalista1: 'FRANCIA', finalista2: 'BRASIL', campeon: 'BRASIL' },
  '54': { finalista1: 'BRASIL', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '55': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '56': { finalista1: 'ESPAÑA', finalista2: 'INGLATERRA', campeon: 'INGLATERRA' },
  '57': { finalista1: 'ALEMANIA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '58': { finalista1: 'FRANCIA', finalista2: 'BRASIL', campeon: 'FRANCIA' },
  '59': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '60': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '61': { finalista1: 'PAÍSES BAJOS', finalista2: 'PORTUGAL', campeon: 'PAÍSES BAJOS' },
  '62': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '63': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '64': { finalista1: 'ESPAÑA', finalista2: 'BRASIL', campeon: 'ESPAÑA' },
  '65': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'FRANCIA' },
  '66': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '67': { finalista1: 'FRANCIA', finalista2: 'BRASIL', campeon: 'FRANCIA' },
  '68': { finalista1: 'ESPAÑA', finalista2: 'INGLATERRA', campeon: 'ESPAÑA' },
  '69': { finalista1: 'FRANCIA', finalista2: 'BRASIL', campeon: 'BRASIL' },
  '70': { finalista1: 'FRANCIA', finalista2: 'BRASIL', campeon: 'FRANCIA' },
  '71': { finalista1: 'ESPAÑA', finalista2: 'ARGENTINA', campeon: 'ESPAÑA' },
  '72': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '73': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '74': { finalista1: 'ESPAÑA', finalista2: 'BRASIL', campeon: 'ESPAÑA' },
  '75': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '76': { finalista1: 'ESPAÑA', finalista2: 'ARGENTINA', campeon: 'ESPAÑA' },
  '77': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '78': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '79': { finalista1: 'ESPAÑA', finalista2: 'FRANCIA', campeon: 'FRANCIA' },
  '80': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '81': { finalista1: 'ESPAÑA', finalista2: 'MARRUECOS', campeon: 'ESPAÑA' },
  '82': { finalista1: 'FRANCIA', finalista2: 'INGLATERRA', campeon: 'FRANCIA' },
  '83': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '84': { finalista1: 'FRANCIA', finalista2: 'INGLATERRA', campeon: 'FRANCIA' },
  '85': { finalista1: 'ESPAÑA', finalista2: 'INGLATERRA', campeon: 'INGLATERRA' },
  '86': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '87': { finalista1: 'ESPAÑA', finalista2: 'INGLATERRA', campeon: 'ESPAÑA' },
  '88': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '89': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '90': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '91': { finalista1: 'PAÍSES BAJOS', finalista2: 'PORTUGAL', campeon: 'PAÍSES BAJOS' },
  '92': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '93': { finalista1: 'ESPAÑA', finalista2: 'INGLATERRA', campeon: 'ESPAÑA' },
  '94': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'FRANCIA' },
  '95': { finalista1: 'FRANCIA', finalista2: 'BRASIL', campeon: 'BRASIL' },
  '96': { finalista1: 'ESPAÑA', finalista2: 'ARGENTINA', campeon: 'ESPAÑA' },
  '97': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'FRANCIA' },
  '98': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'PORTUGAL' },
  '99': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'FRANCIA' },
  '100': { finalista1: 'ESPAÑA', finalista2: 'ARGENTINA', campeon: 'ARGENTINA' },
  '101': { finalista1: 'PAÍSES BAJOS', finalista2: 'PORTUGAL', campeon: 'PAÍSES BAJOS' },
  '102': { finalista1: 'ESPAÑA', finalista2: 'INGLATERRA', campeon: 'ESPAÑA' },
  '103': { finalista1: 'ESPAÑA', finalista2: 'INGLATERRA', campeon: 'ESPAÑA' },
  '104': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
  '105': { finalista1: 'FRANCIA', finalista2: 'PORTUGAL', campeon: 'FRANCIA' },
  '106': { finalista1: 'ESPAÑA', finalista2: 'PORTUGAL', campeon: 'ESPAÑA' },
};
